¿OKR: Proposito?

Exploración de datos: (EDA)
1. Revisar estructura, tamaño, los tipos de datos
2. detectar, identificar nulos, cardinalidades, duplicados
3. Analizar las variables categóricas y númericas
4. detectar formatos de fechas no están estandarizados, homogeneidad
5. outliers o datos atipicos
6. tipografía (formato, todo se maneja upper, lower)
7. perfil de la calidad del dato
8. generar reportes de ese eda, gráficas, histo, tablas

In [1]:
# ANALISIS DE ARCHIVO CON COLUMNAS RENOMBRADAS
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import yaml
from pathlib import Path

ROOT = Path.cwd().resolve()
if not (ROOT / "config" / "config.yaml").is_file():
    ROOT = ROOT.parent
config_path = ROOT / "config" / "config.yaml"
if not config_path.is_file():
    raise FileNotFoundError("No se encontro config/config.yaml desde la carpeta actual.")
with config_path.open("r", encoding="utf-8") as file:
    config = yaml.safe_load(file)
silver_dir = ROOT / config["paths"]["silver_dir"]

caracteristicas_generales = pd.read_csv(
    silver_dir / config["source"]["csv_salida_cg_transformado"], low_memory=False
)
print("Caracteristicas generales")
display(caracteristicas_generales.head(20))
display(caracteristicas_generales.shape)
display(caracteristicas_generales.info())
display(caracteristicas_generales.describe())

Caracteristicas generales

,Unnamed: 0,Periodo_Recoleccion,Mes_Encuesta,Anio_Encuesta,Id_Vivienda,Id_Hogar,Orden_Persona,Numero_Hogar,Area_Metropolitana,Factor_Expansion,Departamento,Sexo_Al_Nacer,Edad,Pago_Mensual_Salud,Nivel_Educativo,Titulo_o_Diploma,Titulo_Diploma_EnQue,Poblacion_Mayor_18
0,0,20251252,12,2025,8435963,1,1,1,NaN,101.661383,8,1,32,NaN,5.0,2.0,NaN,1.0
1,1,20251252,12,2025,8435963,1,2,1,NaN,101.661383,8,2,28,NaN,8.0,5.0,419.0,1.0
2,2,20251252,12,2025,8435963,1,3,1,NaN,101.661383,8,1,0,NaN,NaN,NaN,NaN,NaN
3,3,20251252,12,2025,8435964,1,1,1,NaN,78.402590,8,1,75,NaN,1.0,NaN,NaN,1.0
4,4,20251252,12,2025,8435965,1,1,1,NaN,78.402590,8,1,68,NaN,3.0,NaN,NaN,1.0
5,5,20251252,12,2025,8435966,1,1,1,NaN,78.402590,8,1,66,NaN,3.0,NaN,NaN,1.0
6,6,20251252,12,2025,8435967,1,1,1,NaN,114.417238,8,1,51,NaN,5.0,2.0,NaN,1.0
7,7,20251252,12,2025,8435968,1,1,1,NaN,78.402590,8,1,59,NaN,4.0,NaN,NaN,1.0
8,8,20251252,12,2025,8435969,1,1,1,NaN,81.534613,8,2,56,NaN,8.0,5.0,731.0,1.0
9,9,20251252,12,2025,8435970,1,1,1,NaN,404.543698,8,1,44,56940.0,5.0,2.0,NaN,1.0
10,10,20251252,12,2025,8435970,1,2,1,NaN,404.543698,8,2,43,NaN,10.0,7.0,411.0,1.0
11,11,20251252,12,2025,8435970,1,3,1,NaN,404.543698,8,1,13,NaN,4.0,NaN,NaN,NaN
12,12,20251252,12,2025,8435970,1,4,1,NaN,404.543698,8,1,11,NaN,4.0,NaN,NaN,NaN
13,13,20251252,12,2025,8435971,1,1,1,NaN,287.785509,8,1,83,56940.0,3.0,NaN,NaN,1.0
14,14,20251252,12,2025,8435972,1,1,1,NaN,287.785509,8,1,72,56940.0,5.0,2.0,NaN,1.0
15,15,20251252,12,2025,8435973,1,1,1,NaN,226.661439,8,2,61,NaN,3.0,NaN,NaN,1.0
16,16,20251252,12,2025,8435973,1,2,1,NaN,226.661439,8,1,71,NaN,5.0,2.0,NaN,1.0
17,17,20251252,12,2025,8435974,1,1,1,NaN,479.556614,8,1,41,NaN,5.0,1.0,NaN,1.0
18,18,20251252,12,2025,8435974,1,2,1,NaN,479.556614,8,1,53,NaN,1.0,NaN,NaN,1.0
19,19,20251252,12,2025,8435975,1,1,1,NaN,287.785509,8,1,70,NaN,1.0,NaN,NaN,1.0

(203851, 18)

<class 'pandas.DataFrame'>
RangeIndex: 203851 entries, 0 to 203850
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Unnamed: 0            203851 non-null  int64
 1   Periodo_Recoleccion   203851 non-null  int64
 2   Mes_Encuesta          203851 non-null  int64
 3   Anio_Encuesta         203851 non-null  int64
 4   Id_Vivienda           203851 non-null  int64
 5   Id_Hogar              203851 non-null  int64
 6   Orden_Persona         203851 non-null  int64
 7   Numero_Hogar          203851 non-null  int64
 8   Area_Metropolitana    147817 non-null  float64
 9   Factor_Expansion      203851 non-null  float64
 10  Departamento          203851 non-null  int64
 11  Sexo_Al_Nacer         203851 non-null  int64
 12  Edad                  203851 non-null  int64
 13  Pago_Mensual_Salud    52289 non-null   float64
 14  Nivel_Educativo       198320 non-null  float64
 15  Titulo_o_Diploma      104226 non-null  float64
 16  Titulo_Diploma_EnQue  39448 non-null   float64
 17  Poblacion_Mayor_18    153766 non-null  float64
dtypes: float64(7), int64(11)
memory usage: 28.0 MB

None

,Unnamed: 0,Periodo_Recoleccion,Mes_Encuesta,Anio_Encuesta,Id_Vivienda,Id_Hogar,Orden_Persona,Numero_Hogar,Area_Metropolitana,Factor_Expansion,Departamento,Sexo_Al_Nacer,Edad,Pago_Mensual_Salud,Nivel_Educativo,Titulo_o_Diploma,Titulo_Diploma_EnQue,Poblacion_Mayor_18
count,203851.0000,2.038510e+05,203851.000000,203851.0,2.038510e+05,203851.000000,203851.000000,203851.000000,147817.000000,203851.000000,203851.000000,203851.000000,203851.000000,5.228900e+04,198320.000000,104226.000000,39448.000000,153766.0
mean,101925.0000,2.025115e+07,10.989448,2025.0,8.420545e+06,1.005936,2.283428,1.005936,41.525332,769.008899,41.128304,1.533414,36.619673,1.477984e+05,5.255577,3.680819,536.301714,1.0
std,58846.8592,8.488126e+01,0.814530,0.0,2.848047e+04,0.089826,1.386471,0.089826,26.685148,1089.502991,25.847487,0.498883,22.281225,4.002012e+05,2.786131,2.317828,283.337758,0.0
min,0.0000,2.025104e+07,10.000000,2025.0,8.374095e+06,1.000000,1.000000,1.000000,5.000000,6.703899,5.000000,1.000000,0.000000,9.800000e+01,1.000000,1.000000,11.000000,1.0
25%,50962.5000,2.025104e+07,10.000000,2025.0,8.395412e+06,1.000000,1.000000,1.000000,17.000000,156.635052,17.000000,1.000000,18.000000,5.700000e+04,3.000000,2.000000,411.000000,1.0
50%,101925.0000,2.025115e+07,11.000000,2025.0,8.420196e+06,1.000000,2.000000,1.000000,44.000000,320.127587,44.000000,2.000000,35.000000,8.000000e+04,5.000000,2.000000,421.000000,1.0
75%,152887.5000,2.025125e+07,12.000000,2025.0,8.442654e+06,1.000000,3.000000,1.000000,66.000000,935.467724,66.000000,2.000000,54.000000,1.780000e+05,8.000000,6.000000,731.000000,1.0
max,203850.0000,2.025125e+07,12.000000,2025.0,8.473908e+06,5.000000,16.000000,5.000000,99.000000,12719.309102,99.000000,2.000000,108.000000,8.000000e+07,99.000000,99.000000,2198.000000,1.0

In [2]:
# ANALISIS EXPLORATORIO DE OCUPADOS
ocupados = pd.read_csv(
    silver_dir / config["source"]["csv_salida_ocupados_transformado"], low_memory=False
)
display(ocupados.head(20))
display(ocupados.shape)
display(ocupados.info())
display(ocupados.describe())

,Unnamed: 0,Periodo_Recoleccion,Mes_Encuesta,Anio_Encuesta,Id_Vivienda,Id_Hogar,Orden_Persona,Numero_Hogar,Area_Metropolitana,Factor_Expansion,Departamento,Categoria_Trabajo,Horas_Trabajo_Semanales,Ingreso_Laboral,Rama_Act_Empleo_Ppal
0,0,20251252,12,2025,8435963,1,1,1,NaN,101.661383,8,4,90,1200000.0,3
1,1,20251252,12,2025,8435963,1,2,1,NaN,101.661383,8,6,56,NaN,56
2,2,20251252,12,2025,8435964,1,1,1,NaN,78.402590,8,4,54,2000000.0,3
3,3,20251252,12,2025,8435965,1,1,1,NaN,78.402590,8,4,48,1800000.0,3
4,4,20251252,12,2025,8435966,1,1,1,NaN,78.402590,8,4,56,2400000.0,3
5,5,20251252,12,2025,8435967,1,1,1,NaN,114.417238,8,4,56,1500000.0,3
6,6,20251252,12,2025,8435968,1,1,1,NaN,78.402590,8,4,42,1650000.0,3
7,7,20251252,12,2025,8435969,1,1,1,NaN,81.534613,8,5,56,2250000.0,56
8,8,20251252,12,2025,8435970,1,1,1,NaN,404.543698,8,1,48,1800000.0,78
9,9,20251252,12,2025,8435973,1,2,1,NaN,226.661439,8,4,40,800000.0,1
10,10,20251252,12,2025,8435974,1,1,1,NaN,479.556614,8,4,56,220000.0,1
11,11,20251252,12,2025,8435975,1,1,1,NaN,287.785509,8,6,28,NaN,1
12,12,20251252,12,2025,8435976,1,1,1,NaN,209.579536,8,4,42,900000.0,1
13,13,20251252,12,2025,8435976,1,2,1,NaN,209.579536,8,3,45,760000.0,97
14,14,20251252,12,2025,8435977,1,1,1,NaN,1668.194253,13,4,20,300000.0,47
15,15,20251252,12,2025,8435977,1,2,1,NaN,1668.194253,13,4,40,400000.0,41
16,16,20251252,12,2025,8435978,1,2,1,NaN,1824.897817,13,4,30,500000.0,41
17,17,20251252,12,2025,8435979,1,1,1,NaN,1282.881521,13,4,40,450000.0,1
18,18,20251252,12,2025,8435979,1,2,1,NaN,1282.881521,13,4,20,150000.0,47
19,19,20251252,12,2025,8435979,1,3,1,NaN,1282.881521,13,4,40,400000.0,56

(91357, 15)

<class 'pandas.DataFrame'>
RangeIndex: 91357 entries, 0 to 91356
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               91357 non-null  int64
 1   Periodo_Recoleccion      91357 non-null  int64
 2   Mes_Encuesta             91357 non-null  int64
 3   Anio_Encuesta            91357 non-null  int64
 4   Id_Vivienda              91357 non-null  int64
 5   Id_Hogar                 91357 non-null  int64
 6   Orden_Persona            91357 non-null  int64
 7   Numero_Hogar             91357 non-null  int64
 8   Area_Metropolitana       67214 non-null  float64
 9   Factor_Expansion         91357 non-null  float64
 10  Departamento             91357 non-null  int64
 11  Categoria_Trabajo        91357 non-null  int64
 12  Horas_Trabajo_Semanales  91357 non-null  int64
 13  Ingreso_Laboral          89469 non-null  float64
 14  Rama_Act_Empleo_Ppal     91357 non-null  int64
dtypes: float64(3), int64(12)
memory usage: 10.5 MB

None

,Unnamed: 0,Periodo_Recoleccion,Mes_Encuesta,Anio_Encuesta,Id_Vivienda,Id_Hogar,Orden_Persona,Numero_Hogar,Area_Metropolitana,Factor_Expansion,Departamento,Categoria_Trabajo,Horas_Trabajo_Semanales,Ingreso_Laboral,Rama_Act_Empleo_Ppal
count,91357.000000,9.135700e+04,91357.000000,91357.0,9.135700e+04,91357.000000,91357.000000,91357.000000,67214.000000,91357.000000,91357.000000,91357.000000,91357.000000,8.946900e+04,91357.000000
mean,45678.000000,2.025115e+07,10.986909,2025.0,8.420420e+06,1.006009,1.755596,1.006009,41.733091,801.163657,41.317611,2.736298,43.358363,1.816172e+06,53.429732
std,26372.638608,8.473843e+01,0.813127,0.0,2.847279e+04,0.091311,1.066010,0.091311,27.219270,1129.021581,26.334126,1.659735,13.258775,2.257874e+06,27.870947
min,0.000000,2.025104e+07,10.000000,2025.0,8.374095e+06,1.000000,1.000000,1.000000,5.000000,6.703899,5.000000,1.000000,1.000000,0.000000e+00,0.000000
25%,22839.000000,2.025104e+07,10.000000,2025.0,8.395422e+06,1.000000,1.000000,1.000000,17.000000,161.134496,17.000000,1.000000,40.000000,8.000000e+05,41.000000
50%,45678.000000,2.025115e+07,11.000000,2025.0,8.420107e+06,1.000000,1.000000,1.000000,44.000000,331.213033,44.000000,3.000000,44.000000,1.423500e+06,49.000000
75%,68517.000000,2.025125e+07,12.000000,2025.0,8.442361e+06,1.000000,2.000000,1.000000,66.000000,976.817406,66.000000,4.000000,48.000000,2.000000e+06,82.000000
max,91356.000000,2.025125e+07,12.000000,2025.0,8.473908e+06,5.000000,13.000000,5.000000,99.000000,12719.309102,99.000000,8.000000,130.000000,9.800000e+07,99.000000

In [3]:
# detectar nulos
print("Cantidad de nulos en caracteristicas generales")
display(caracteristicas_generales.isnull().sum())
print("Cantidad de nulos en ocupados")
display(ocupados.isnull().sum())

Cantidad de nulos en caracteristicas generales

Unnamed: 0                   0
Periodo_Recoleccion          0
Mes_Encuesta                 0
Anio_Encuesta                0
Id_Vivienda                  0
Id_Hogar                     0
Orden_Persona                0
Numero_Hogar                 0
Area_Metropolitana       56034
Factor_Expansion             0
Departamento                 0
Sexo_Al_Nacer                0
Edad                         0
Pago_Mensual_Salud      151562
Nivel_Educativo           5531
Titulo_o_Diploma         99625
Titulo_Diploma_EnQue    164403
Poblacion_Mayor_18       50085
dtype: int64

Cantidad de nulos en ocupados

Unnamed: 0                     0
Periodo_Recoleccion            0
Mes_Encuesta                   0
Anio_Encuesta                  0
Id_Vivienda                    0
Id_Hogar                       0
Orden_Persona                  0
Numero_Hogar                   0
Area_Metropolitana         24143
Factor_Expansion               0
Departamento                   0
Categoria_Trabajo              0
Horas_Trabajo_Semanales        0
Ingreso_Laboral             1888
Rama_Act_Empleo_Ppal           0
dtype: int64