¿OKR: Proposito?

Exploración de datos: (EDA)
1. Revisar estructura, tamaño, los tipos de datos
2. detectar, identificar nulos, cardinalidades, duplicados
3. Analizar las variables categóricas y númericas
4. detectar formatos de fechas no están estandarizados, homogeneidad
5. outliers o datos atipicos
6. tipografía (formato, todo se maneja upper, lower)
7. perfil de la calidad del dato
8. generar reportes de ese eda, gráficas, histo, tablas

In [ ]:
#ANALISIS DE ARCHIVO CGENERALES CON COLUMNAS RENOMBRADAS
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import yaml
from pathlib import Path

ROOT = Path.cwd().resolve()
if not (ROOT / "config" / "config.yaml").is_file():
    ROOT = ROOT.parent
config_path = ROOT / "config" / "config.yaml"
if not config_path.is_file():
    raise FileNotFoundError("No se encontro config/config.yaml desde la carpeta actual.")
with config_path.open("r", encoding="utf-8") as file:
    config = yaml.safe_load(file)
bronze_dir = ROOT / config["paths"]["bronze_dir"]
silver_dir = ROOT / config["paths"]["silver_dir"]

caracteristicas_generales = pd.read_csv(bronze_dir / config["source"]["csv_salida_cg"], low_memory=False)
print("Caracteristicas generales")
display(caracteristicas_generales.head(20))
display(caracteristicas_generales.shape)
display(caracteristicas_generales.info())    
display(caracteristicas_generales.describe())

In [ ]:
#ANALISIS EXPLORATORIO DE DATOS DE ARCHIVO CGENERALES SIN RENOMBRAR COLUMNAS
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import yaml
caracteristicas_generales = pd.read_csv(bronze_dir / config["source"]["csv_salida_cg_sinrenombrar"], low_memory=False)
print("Caracteristicas generales")
display(caracteristicas_generales.head(20))
display(caracteristicas_generales.shape)
display(caracteristicas_generales.info())    
display(caracteristicas_generales.describe())

In [ ]:
#ANALISIS EXPLORATORIO DE DATOS DE ARCHIVO OCUPADOS SIN RENOMBRAR COLUMNAS
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import yaml

ocupados = pd.read_csv(bronze_dir / config["source"]["csv_salida_ocupados_sinrenombrar"], low_memory=False)
display(ocupados.head(20))
display(ocupados.shape)
display(ocupados.info())    
display(ocupados.describe())

In [4]:
#ANALISIS EXPLORATORIO DE DATOS DE ARCHIVO OCUPADOS CON COLUMNAS RENOMBRADAS
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import yaml

ocupados = pd.read_csv(bronze_dir / config["source"]["csv_salida_ocupados"], low_memory=False)
display(ocupados.head(20))
display(ocupados.shape)
display(ocupados.info())    
display(ocupados.describe())

,Unnamed: 0,Periodo_Recoleccion,Mes_Encuesta,Anio_Encuesta,Id_Vivienda,Id_Hogar,Orden_Persona,Numero_Hogar,Tipo_Registro,Area_Metropolitana,...,Medio_Transporte_Trabajo,Otro_Medio_Transporte,Minutos_Desplazamiento_Trabajo,Fuente_Recursos_Sin_Trabajo,Otra_Fuente_Recursos_Sin_Trabajo,Indicador_Ocupado,Ingreso_Laboral,Rama_Act_Empleo_Ppal,Rama_Act_Empleo_Ppal_4_Digitos,Oficio_Clasificado
0,0,20251252,12,2025,8435963,1,1,1,60,NaN,...,9,NaN,5.0,8,NaN,1,1200000.0,3,311,6223
1,1,20251252,12,2025,8435963,1,2,1,60,NaN,...,11,NaN,20.0,3,NaN,1,NaN,56,5611,9412
2,2,20251252,12,2025,8435964,1,1,1,60,NaN,...,9,NaN,30.0,3,NaN,1,2000000.0,3,311,6222
3,3,20251252,12,2025,8435965,1,1,1,60,NaN,...,9,NaN,25.0,3,NaN,1,1800000.0,3,311,6222
4,4,20251252,12,2025,8435966,1,1,1,60,NaN,...,9,NaN,20.0,3,NaN,1,2400000.0,3,311,6222
5,5,20251252,12,2025,8435967,1,1,1,60,NaN,...,9,NaN,30.0,9,NaN,1,1500000.0,3,311,6223
6,6,20251252,12,2025,8435968,1,1,1,60,NaN,...,9,NaN,25.0,3,NaN,1,1650000.0,3,311,6222
7,7,20251252,12,2025,8435969,1,1,1,60,NaN,...,3,NaN,3.0,3,NaN,1,2250000.0,56,5611,1412
8,8,20251252,12,2025,8435970,1,1,1,60,NaN,...,1,NaN,30.0,5,NaN,1,1800000.0,78,7820,4415
9,9,20251252,12,2025,8435973,1,2,1,60,NaN,...,3,NaN,10.0,2,NaN,1,800000.0,1,145,6122
10,10,20251252,12,2025,8435974,1,1,1,60,NaN,...,11,NaN,20.0,3,NaN,1,220000.0,1,161,9211
11,11,20251252,12,2025,8435975,1,1,1,60,NaN,...,3,NaN,5.0,3,NaN,1,NaN,1,145,9213
12,12,20251252,12,2025,8435976,1,1,1,60,NaN,...,3,NaN,15.0,3,NaN,1,900000.0,1,161,9213
13,13,20251252,12,2025,8435976,1,2,1,60,NaN,...,11,NaN,15.0,3,NaN,1,760000.0,97,9700,9111
14,14,20251252,12,2025,8435977,1,1,1,60,NaN,...,14,NaN,NaN,5,NaN,1,300000.0,47,4719,5223
15,15,20251252,12,2025,8435977,1,2,1,60,NaN,...,3,NaN,5.0,5,NaN,1,400000.0,41,4111,9313
16,16,20251252,12,2025,8435978,1,2,1,60,NaN,...,3,NaN,5.0,9,NaN,1,500000.0,41,4111,9313
17,17,20251252,12,2025,8435979,1,1,1,60,NaN,...,3,NaN,15.0,5,NaN,1,450000.0,1,113,6111
18,18,20251252,12,2025,8435979,1,2,1,60,NaN,...,14,NaN,NaN,5,NaN,1,150000.0,47,4789,9520
19,19,20251252,12,2025,8435979,1,3,1,60,NaN,...,3,NaN,5.0,5,NaN,1,400000.0,56,5630,5223

(91357, 203)

<class 'pandas.DataFrame'>
RangeIndex: 91357 entries, 0 to 91356
Columns: 203 entries, Unnamed: 0 to Oficio_Clasificado
dtypes: float64(150), int64(41), str(12)
memory usage: 141.5 MB

None

,Unnamed: 0,Periodo_Recoleccion,Mes_Encuesta,Anio_Encuesta,Id_Vivienda,Id_Hogar,Orden_Persona,Numero_Hogar,Tipo_Registro,Area_Metropolitana,...,Trabajo_Estable,Compatibilidad_Horario_Familia,Medio_Transporte_Trabajo,Minutos_Desplazamiento_Trabajo,Fuente_Recursos_Sin_Trabajo,Indicador_Ocupado,Ingreso_Laboral,Rama_Act_Empleo_Ppal,Rama_Act_Empleo_Ppal_4_Digitos,Oficio_Clasificado
count,91357.000000,9.135700e+04,91357.000000,91357.0,9.135700e+04,91357.000000,91357.000000,91357.000000,91357.0,67214.000000,...,91357.000000,91357.000000,91357.000000,78336.000000,91357.000000,91357.0,8.946900e+04,91357.000000,91357.000000,91357.000000
mean,15231.525411,2.025115e+07,10.986909,2025.0,8.420420e+06,1.006009,1.755596,1.006009,60.0,41.733091,...,1.265420,1.098121,8.043489,24.000843,4.339777,1.0,1.816172e+06,53.429732,5370.550500,5899.617172
std,8800.929123,8.473843e+01,0.813127,0.0,2.847279e+04,0.091311,1.066010,0.091311,0.0,27.219270,...,0.441559,0.297479,4.504686,24.333218,2.525959,0.0,2.257874e+06,27.870947,2782.516414,2571.150336
min,0.000000,2.025104e+07,10.000000,2025.0,8.374095e+06,1.000000,1.000000,1.000000,60.0,5.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,0.000000e+00,0.000000,0.000000,0.000000
25%,7613.000000,2.025104e+07,10.000000,2025.0,8.395422e+06,1.000000,1.000000,1.000000,60.0,17.000000,...,1.000000,1.000000,3.000000,10.000000,3.000000,1.0,8.000000e+05,41.000000,4111.000000,4110.000000
50%,15226.000000,2.025115e+07,11.000000,2025.0,8.420107e+06,1.000000,1.000000,1.000000,60.0,44.000000,...,1.000000,1.000000,11.000000,20.000000,3.000000,1.0,1.423500e+06,49.000000,4921.000000,5311.000000
75%,22839.000000,2.025125e+07,12.000000,2025.0,8.442361e+06,1.000000,2.000000,1.000000,60.0,66.000000,...,2.000000,1.000000,11.000000,30.000000,8.000000,1.0,2.000000e+06,82.000000,8220.000000,8323.000000
max,30938.000000,2.025125e+07,12.000000,2025.0,8.473908e+06,5.000000,13.000000,5.000000,60.0,99.000000,...,2.000000,2.000000,15.000000,300.000000,10.000000,1.0,9.800000e+07,99.000000,9900.000000,9629.000000

In [15]:
# detectar nulos
print("Cantidad de nulos en caracteristicas generales")
display(caracteristicas_generales.isnull().sum())
print("Cantidad de nulos en ocupados")
display(ocupados.isnull().sum())

Cantidad de nulos en caracteristicas generales

Unnamed: 0                           0
Periodo_Recoleccion                  0
Mes_Encuesta                         0
Anio_Encuesta                        0
Id_Vivienda                          0
Id_Hogar                             0
Orden_Persona                        0
Numero_Hogar                         0
Tipo_Registro                        0
Area_Metropolitana               56034
Clase_Dominio                        0
Factor_Expansion                     0
Departamento                         0
Poblacion_Total                      0
Orden_Informante                     0
Sexo_Al_Nacer                        0
Edad                                 0
Mes_Nacimiento                     943
Anio_Nacimiento                    943
Parentesco_Jefe_Hogar                0
Madre_Reside_Hogar                   0
Orden_Madre                     128068
Padre_Reside_Hogar                   0
Orden_Padre                     164507
Se_Considera_Campesino               0
Fue_Campesino                    61925
Comunidad_Campesina                  0
Autorreconocimiento_Etnico           0
Pueblo_Indigena                 194493
Otro_Pueblo_Indigena            203851
Estado_Conyugal                  24574
Conyuge_Reside_Hogar            125274
Orden_Conyuge                   129469
Afiliacion_Salud                     0
Regimen_Salud                     6212
Quien_Paga_Salud                114557
Pago_Mensual_Salud              151562
Dificultad_Oir                       0
Dificultad_Hablar                    0
Dificultad_Ver                       0
Dificultad_Movilidad                 0
Dificultad_Manipular_Objetos         0
Dificultad_Cognitiva                 0
Dificultad_Autocuidado               0
Dificultad_Interaccion               0
Sabe_Leer_Escribir                5531
Asiste_Institucion_Educativa      5531
Tipo_Institucion_Educativa      152345
Nivel_Educativo                   5531
Grado_Aprobado                    5531
Area_Nivel_Educativo            153351
Titulo_o_Diploma                 99625
Titulo_Diploma_EnQue            164403
Atraccion_Sexual_Romantica       50085
Identidad_Autorreconocida        50085
Poblacion_Mayor_18               50085
dtype: int64

Cantidad de nulos en ocupados

Unnamed: 0       0
PERIODO          0
MES              0
PER              0
DIRECTORIO       0
              ...
OCI              0
INGLABO       1888
RAMA2D_R4        0
RAMA4D_R4        0
OFICIO_C8        0
Length: 203, dtype: int64


    #------------------
    #Transformacion
    #------------------

In [ ]:
#Analisis de primera transformacion con columnas renombradas. 
df_caracteristicas_generales = pd.read_csv(silver_dir / config["source"]["csv_salida_cg_transformado"], low_memory=False)
print("Caracteristicas generales Transformado")
display(df_caracteristicas_generales .head(200))
display(df_caracteristicas_generales .shape)
display(df_caracteristicas_generales .info())    
display(df_caracteristicas_generales .describe())
print("Despues de quitar duplicados")
df_caracteristicas_generales.dropna()
print(df_caracteristicas_generales)

In [ ]:
#Analisis de primera transformacion con columnas renombradas. 
df_ocupados_transformado = pd.read_csv(silver_dir / config["source"]["csv_salida_ocupados_transformado"], low_memory=False)
print("Ocupados Transformado")
display(df_ocupados_transformado.head(100))
display(df_ocupados_transformado.iloc[len(df_ocupados_transformado)//2 : len(df_ocupados_transformado)//2 + 100])
display(df_ocupados_transformado.shape)
display(df_ocupados_transformado.info())    
display(df_ocupados_transformado.describe())
print("Despues de duplicados")
df_ocupados_transformado.dropna()
print(df_ocupados_transformado)

In [ ]:
# detectar nulos de archivos transformados
print("Cantidad de nulos en caracteristicas generales")
display(df_caracteristicas_generales .isnull().sum())
print("Cantidad de nulos en ocupados")
display(df_ocupados_transformado.isnull().sum())

In [ ]:
#Analisis de dataset unido (cg + ocupados)
df_unidos = pd.read_csv(silver_dir / config["source"]["csv_salida_datasets_unidos"], low_memory=False)
display(df_unidos.head(200))
display(df_unidos.shape)
display(df_unidos.info())    
display(df_unidos.describe())

In [ ]:
#Analisis de dataset con valores traducidos
df_traducido = pd.read_excel(
silver_dir / config["source"]["excel_salida_datasets_traducido"]
)
display(df_traducido.head(20))
display(df_traducido.shape)
display(df_traducido.info())    
display(df_traducido.describe())

In [18]:
#Analisis de dataset con limpieza de columnas
df_traducido_clean = pd.read_excel(
silver_dir / config["source"]["excel_salida_datasets_traducido_clean"]
)
display(df_traducido_clean.head(20))
display(df_traducido_clean.shape)
display(df_traducido_clean.info())    
display(df_traducido_clean.describe())

,Periodo_Recoleccion,Mes_Encuesta,Anio_Encuesta,Id_Vivienda,Id_Hogar,Orden_Persona,Numero_Hogar,Area_Metropolitana,Factor_Expansion,Departamento,Sexo_Al_Nacer,Edad,Nivel_Educativo,Titulo_o_Diploma,Poblacion_Mayor_18,Categoria_Trabajo,Horas_Trabajo_Semanales,Ingreso_Laboral,Rama_Act_Empleo_Ppal
0,20251252,12,2025,8435963,1,1,1,otros,101.661383,ATLANTICO,Masculino,32,Media académica (Bachillerato clásico),Media académica (Bachillerato clásico),1,Trabajador por cuenta propia,90,1200000.0,otras ramas
1,20251252,12,2025,8435963,1,2,1,otros,101.661383,ATLANTICO,Femenino,28,Técnica profesional,Técnica profesional,1,Trabajador familiar sin remuneración,56,NaN,otras ramas
2,20251252,12,2025,8435964,1,1,1,otros,78.402590,ATLANTICO,Masculino,75,Ninguno,sin diploma,1,Trabajador por cuenta propia,54,2000000.0,otras ramas
3,20251252,12,2025,8435965,1,1,1,otros,78.402590,ATLANTICO,Masculino,68,Básica primaria (1o - 5o),sin diploma,1,Trabajador por cuenta propia,48,1800000.0,otras ramas
4,20251252,12,2025,8435966,1,1,1,otros,78.402590,ATLANTICO,Masculino,66,Básica primaria (1o - 5o),sin diploma,1,Trabajador por cuenta propia,56,2400000.0,otras ramas
5,20251252,12,2025,8435967,1,1,1,otros,114.417238,ATLANTICO,Masculino,51,Media académica (Bachillerato clásico),Media académica (Bachillerato clásico),1,Trabajador por cuenta propia,56,1500000.0,otras ramas
6,20251252,12,2025,8435968,1,1,1,otros,78.402590,ATLANTICO,Masculino,59,Básica secundaria (6o - 9o),sin diploma,1,Trabajador por cuenta propia,42,1650000.0,otras ramas
7,20251252,12,2025,8435969,1,1,1,otros,81.534613,ATLANTICO,Femenino,56,Técnica profesional,Técnica profesional,1,Patrón o empleador,56,2250000.0,otras ramas
8,20251252,12,2025,8435970,1,1,1,otros,404.543698,ATLANTICO,Masculino,44,Media académica (Bachillerato clásico),Media académica (Bachillerato clásico),1,Obrero o empleado de empresa particular,48,1800000.0,otras ramas
9,20251252,12,2025,8435973,1,2,1,otros,226.661439,ATLANTICO,Masculino,71,Media académica (Bachillerato clásico),Media académica (Bachillerato clásico),1,Trabajador por cuenta propia,40,800000.0,otras ramas
10,20251252,12,2025,8435974,1,1,1,otros,479.556614,ATLANTICO,Masculino,41,Media académica (Bachillerato clásico),Ninguno,1,Trabajador por cuenta propia,56,220000.0,otras ramas
11,20251252,12,2025,8435975,1,1,1,otros,287.785509,ATLANTICO,Masculino,70,Ninguno,sin diploma,1,Trabajador familiar sin remuneración,28,NaN,otras ramas
12,20251252,12,2025,8435976,1,1,1,otros,209.579536,ATLANTICO,Masculino,56,Básica primaria (1o - 5o),sin diploma,1,Trabajador por cuenta propia,42,900000.0,otras ramas
13,20251252,12,2025,8435976,1,2,1,otros,209.579536,ATLANTICO,Femenino,45,Media académica (Bachillerato clásico),Media académica (Bachillerato clásico),1,Empleado doméstico,45,760000.0,otras ramas
14,20251252,12,2025,8435977,1,1,1,otros,1668.194253,BOLIVAR,Femenino,41,Media académica (Bachillerato clásico),Media académica (Bachillerato clásico),1,Trabajador por cuenta propia,20,300000.0,otras ramas
15,20251252,12,2025,8435977,1,2,1,otros,1668.194253,BOLIVAR,Masculino,42,Básica secundaria (6o - 9o),sin diploma,1,Trabajador por cuenta propia,40,400000.0,otras ramas
16,20251252,12,2025,8435978,1,2,1,otros,1824.897817,BOLIVAR,Masculino,28,Ninguno,sin diploma,1,Trabajador por cuenta propia,30,500000.0,otras ramas
17,20251252,12,2025,8435979,1,1,1,otros,1282.881521,BOLIVAR,Masculino,60,Básica primaria (1o - 5o),sin diploma,1,Trabajador por cuenta propia,40,450000.0,otras ramas
18,20251252,12,2025,8435979,1,2,1,otros,1282.881521,BOLIVAR,Femenino,60,Básica secundaria (6o - 9o),sin diploma,1,Trabajador por cuenta propia,20,150000.0,otras ramas
19,20251252,12,2025,8435979,1,3,1,otros,1282.881521,BOLIVAR,Masculino,21,Básica secundaria (6o - 9o),sin diploma,1,Trabajador por cuenta propia,40,400000.0,otras ramas

(91357, 19)

<class 'pandas.DataFrame'>
RangeIndex: 91357 entries, 0 to 91356
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Periodo_Recoleccion      91357 non-null  int64
 1   Mes_Encuesta             91357 non-null  int64
 2   Anio_Encuesta            91357 non-null  int64
 3   Id_Vivienda              91357 non-null  int64
 4   Id_Hogar                 91357 non-null  int64
 5   Orden_Persona            91357 non-null  int64
 6   Numero_Hogar             91357 non-null  int64
 7   Area_Metropolitana       91357 non-null  str
 8   Factor_Expansion         91357 non-null  float64
 9   Departamento             91357 non-null  str
 10  Sexo_Al_Nacer            91357 non-null  str
 11  Edad                     91357 non-null  int64
 12  Nivel_Educativo          91357 non-null  str
 13  Titulo_o_Diploma         91357 non-null  str
 14  Poblacion_Mayor_18       91357 non-null  int64
 15  Categoria_Trabajo        91357 non-null  str
 16  Horas_Trabajo_Semanales  91357 non-null  int64
 17  Ingreso_Laboral          89469 non-null  float64
 18  Rama_Act_Empleo_Ppal     91357 non-null  str
dtypes: float64(2), int64(10), str(7)
memory usage: 13.2 MB

None

,Periodo_Recoleccion,Mes_Encuesta,Anio_Encuesta,Id_Vivienda,Id_Hogar,Orden_Persona,Numero_Hogar,Factor_Expansion,Edad,Poblacion_Mayor_18,Horas_Trabajo_Semanales,Ingreso_Laboral
count,9.135700e+04,91357.000000,91357.0,9.135700e+04,91357.000000,91357.000000,91357.000000,91357.000000,91357.000000,91357.000000,91357.000000,8.946900e+04
mean,2.025115e+07,10.986909,2025.0,8.420420e+06,1.006009,1.755596,1.006009,801.163657,41.890036,0.992382,43.358363,1.816172e+06
std,8.473843e+01,0.813127,0.0,2.847279e+04,0.091311,1.066010,0.091311,1129.021581,14.261745,0.086951,13.258775,2.257874e+06
min,2.025104e+07,10.000000,2025.0,8.374095e+06,1.000000,1.000000,1.000000,6.703899,15.000000,0.000000,1.000000,0.000000e+00
25%,2.025104e+07,10.000000,2025.0,8.395422e+06,1.000000,1.000000,1.000000,161.134496,30.000000,1.000000,40.000000,8.000000e+05
50%,2.025115e+07,11.000000,2025.0,8.420107e+06,1.000000,1.000000,1.000000,331.213033,41.000000,1.000000,44.000000,1.423500e+06
75%,2.025125e+07,12.000000,2025.0,8.442361e+06,1.000000,2.000000,1.000000,976.817406,53.000000,1.000000,48.000000,2.000000e+06
max,2.025125e+07,12.000000,2025.0,8.473908e+06,5.000000,13.000000,5.000000,12719.309102,100.000000,1.000000,130.000000,9.800000e+07

In [17]:
# detectar nulos
print("Cantidad de nulos en dataset unido y con valores reemplazados")
display(df_traducido_clean .isnull().sum())

Cantidad de nulos en dataset unido y con valores reemplazados

Periodo_Recoleccion           0
Mes_Encuesta                  0
Anio_Encuesta                 0
Id_Vivienda                   0
Id_Hogar                      0
Orden_Persona                 0
Numero_Hogar                  0
Area_Metropolitana            0
Factor_Expansion              0
Departamento                  0
Sexo_Al_Nacer                 0
Edad                          0
Nivel_Educativo               0
Titulo_o_Diploma              0
Poblacion_Mayor_18            0
Categoria_Trabajo             0
Horas_Trabajo_Semanales       0
Ingreso_Laboral            1888
Rama_Act_Empleo_Ppal          0
dtype: int64